
name: py39
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - ipykernel
  - libcxx=12.0.0
  - libffi>=3.3
  - ncurses=6.3
  - make=4.3
  - openssl=1.1.1q
  - pip=21.2.4
  - python=3.9.13
  - python_abi=3.9
  - readline=8.1.2
  - libzlib=1.2.13
  - rust=1.67.1
  - setuptools=61.2.0
  - sqlite>=3.38.3
  - tk>=8.6.11
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib>=1.2.12
  - pip:
      - alabaster==0.7.12
      - babel==2.10.1
      - charset-normalizer==2.0.12
      - docutils==0.17.1
      - idna==3.3
      - imagesize==1.3.0
      - importlib-metadata==4.11.3
      - jupyter==1.0.0
      - markdown-it-py==2.1.0
      - markupsafe==2.1.1
      - matplotlib==3.7.1
      - maturin==0.14.17
      - mdit-py-plugins==0.3.0
      - mdurl==0.1.1
      - myst-parser==0.17.2
      - packaging==21.3
      - pandas==2.0.2
      - patchelf==0.17.2.1
      - poetry==1.2.0
      - pygments==2.12.0
      - pyparsing==3.0.8
      - pytz==2022.1
      - pyyaml==6.0
      - pydata-sphinx-theme==0.13.3
      - pyvis==0.3.2
      - requests==2.27.1
      - snowballstemmer==2.2.0
      - nbsphinx>=0.8.7
      - sphinx==4.5.0
      - sphinx-rtd-theme==1.0.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinx-tabs==3.4.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - typing-extensions==4.2.0
      - urllib3==1.26.9
      - zipp==3.8.0
