version: '3.3'

services:
    #### Monitoring front-end ####
    prometheus:
        build: prometheus/
        image: miratepuffin/raphtory_prometheus
        ports:
            - 8888:9090
        volumes:
            - prometheus_data:/prometheus
            - ./charts_html:/usr/share/prometheus/consoles
        env_file: .env
        deploy:
            endpoint_mode: vip
            replicas: 1

    #### runZoo ####
    zooKeeper:
        image: quay.io/miratepuffin/zookeeper:latest
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        deploy:
            endpoint_mode: vip
            replicas: 1

    #### seedSetup ####
    seedNode:
       image: miratepuffin/raphtory
       depends_on: 
            - zooKeeper
       command: env-setter.sh seedNode
       env_file: .env
       deploy:
          endpoint_mode: dnsrr
          replicas: 1

    #### Machines Setup ####
    partitionManager:
        image: miratepuffin/raphtory
        depends_on: 
            - seedNode
            - watchDog
        command: env-setter.sh partitionManager
        env_file: .env
        deploy:
            endpoint_mode: dnsrr
            replicas: 1 #$NUMBER_OF_PARTITIONS

    router:
        image: miratepuffin/raphtory
        depends_on: 
            - partitionManager
        command: env-setter.sh router
        env_file: .env
        deploy:
            endpoint_mode: dnsrr
            replicas: 1

    updater:
        image: miratepuffin/raphtory
        depends_on:
            - router
        command: env-setter.sh updater
        env_file: .env
        deploy:
            replicas: 1

    watchDog:
        image: miratepuffin/raphtory
        depends_on: 
            - seedNode
        command: env-setter.sh clusterUp
        env_file: .env
        deploy:
            endpoint_mode: vip
            replicas: 1

#    lam:
#        image: miratepuffin/raphtory
#        depends_on: 
#            - clusterUp
#        ports:
#            - 9105:9105
#        command: LiveAnalysisManager $NUMBER_OF_PARTITIONS $ZOOKEEPER $LAM_NAME
#        environment:
#            - BIND_PORT=9105
#            - HOST_PORT=9105
#            - HOST_IP=raphtory_lam_1
#    rest:
#       image: miratepuffin/raphtory
#       depends_on: 
#            - seedNode
#       ports:
#            - 8080:8080
#       command: rest $ZOOKEEPER
#       environment:
#            - BIND_PORT=9101
#            - HOST_PORT=9101
#            - HOST_IP=raphtory_rest_1

volumes:
    prometheus_data:
