name: Run the scala and python tests
on:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  call-test-scala-python-workflow-in-local-repo:
    uses: ./.github/workflows/test_scala_python_workflow.yml
    secrets: inherit
