global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9999
    - host.docker.internal:1737
    - host.docker.internal:1738
    - host.docker.internal:1739
    - host.docker.internal:1740
    - host.docker.internal:1741
    - host.docker.internal:1742
    - host.docker.internal:1743
    - host.docker.internal:1744
    - host.docker.internal:1745
    - host.docker.internal:1746
    - host.docker.internal:1747
